### ISSUE TITLE
Release pre-compiled packages for macOS M1/M2/M3

### ISSUE THREAD

**Issue by cjordan** [MWATelescope/mwa_hyperbeam#7]
Hey @gsleap or @d3v-null, just flagging this related to #6.

**Comment by d3v-null** [comment]
Thanks @cjordan , I've been testing this out on mwalib ( https://github.com/MWATelescope/mwalib/commit/13c2cce00de5a220cecae8e6f1354af9d6bf8507 ) and it seems to work. We'll need https://github.com/pkgw/rubbl/issues/345 to get it working on Marlu and hyperdrive
